# Generated by Django 5.2 on 2025-05-06 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(blank=True, max_length=20, null=True)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=dict)),
                ('correct_answer', models.CharField(max_length=10)),
                ('subspecialty', models.CharField(max_length=100)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, choices=[('Part I', 'Part I'), ('Part II', 'Part II'), ('Promotion', 'Promotion'), ('Other', 'Other')], max_length=50, null=True)),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=1)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
            ],
            options={
                'unique_together': {('user', 'mcq')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
            ],
            options={
                'unique_together': {('user', 'mcq')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mcq')},
            },
        ),
    ]
