# Generated by Django 5.2 on 2025-05-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=5)),
                ('is_correct', models.BooleanField(default=False)),
                ('user_reasoning', models.TextField()),
                ('satisfaction_level', models.CharField(blank=True, choices=[('very_helpful', 'Very Helpful'), ('somewhat_helpful', 'Somewhat Helpful'), ('not_helpful', 'Not Helpful')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
