# Generated by Django 5.2 on 2025-05-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_reasoningsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
