# Generated by Django 5.2 on 2025-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_alter_mcq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasoningsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='guidance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
