# Generated by Django 5.2 on 2025-05-08 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_hiddenmcq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Date when this account expires', null=True)),
                ('is_active_override', models.BooleanField(default=True, help_text='Manual override for account activation status')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.AlterModelOptions(
            name='mcq',
            options={'verbose_name': 'MCQ', 'verbose_name_plural': 'MCQs'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='reasoningsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reasoning Session', 'verbose_name_plural': 'Reasoning Sessions'},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this interaction was created'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='mcq',
            field=models.ForeignKey(help_text='The associated MCQ', on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(help_text='User who interacted with this MCQ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this interaction was created'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='Spaced repetition ease factor (higher means easier to remember)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1, help_text='Current interval in days between reviews'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, help_text='When this flashcard was last reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='mcq',
            field=models.ForeignKey(help_text='The associated MCQ', on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this flashcard is due for review', null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(help_text='User who interacted with this MCQ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hiddenmcq',
            name='hidden_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this MCQ was hidden'),
        ),
        migrations.AlterField(
            model_name='hiddenmcq',
            name='mcq',
            field=models.ForeignKey(help_text='The MCQ that was hidden', on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq'),
        ),
        migrations.AlterField(
            model_name='hiddenmcq',
            name='user',
            field=models.ForeignKey(help_text='User who hid this MCQ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='correct_answer',
            field=models.CharField(help_text='Letter of the correct answer option (A, B, C, D, etc.)', max_length=5),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Part I', 'Part I'), ('Part II', 'Part II'), ('Promotion', 'Promotion'), ('Other', 'Other')], db_index=True, help_text='Type of exam this question appeared in', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='exam_year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Year the question appeared in an exam', null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed explanation of the answer', null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text="Answer options stored as JSON, e.g., {'A': 'Option text', 'B': 'Option text'}", null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question_number',
            field=models.CharField(blank=True, db_index=True, help_text="Unique identifier for the question, e.g., 'Q123'", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question_text',
            field=models.TextField(help_text='The full text of the question'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='source_file',
            field=models.CharField(blank=True, help_text='Original source file or reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='subspecialty',
            field=models.CharField(db_index=True, help_text='Neurological subspecialty this question belongs to', max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this interaction was created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='mcq',
            field=models.ForeignKey(help_text='The associated MCQ', on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(help_text="User's notes about this MCQ"),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this note was last updated'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(help_text='User who interacted with this MCQ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this reasoning session occurred'),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='guidance',
            field=models.TextField(blank=True, help_text='AI-generated guidance on the clinical reasoning', null=True),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Whether the selected answer was correct'),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='mcq',
            field=models.ForeignKey(help_text='The MCQ being analyzed', on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq'),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='satisfaction_level',
            field=models.CharField(blank=True, choices=[('very_helpful', 'Very Helpful'), ('somewhat_helpful', 'Somewhat Helpful'), ('not_helpful', 'Not Helpful')], help_text="User's satisfaction with the AI guidance", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='selected_answer',
            field=models.CharField(help_text='The answer option the user selected', max_length=5),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='user',
            field=models.ForeignKey(help_text='User who participated in this reasoning session', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='user_reasoning',
            field=models.TextField(help_text="User's explanation of their reasoning process"),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'next_review'], name='mcq_flashca_user_id_09f3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='hiddenmcq',
            index=models.Index(fields=['user'], name='mcq_hiddenm_user_id_9da5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['subspecialty', 'exam_type'], name='mcq_mcq_subspec_9a64f2_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['question_number'], name='mcq_mcq_questio_f0d3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningsession',
            index=models.Index(fields=['user', 'created_at'], name='mcq_reasoni_user_id_56fbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningsession',
            index=models.Index(fields=['user', 'mcq'], name='mcq_reasoni_user_id_3df86b_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['expiration_date'], name='mcq_userpro_expirat_2e6558_idx'),
        ),
    ]
