# Generated by Django 5.2 on 2025-05-09 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_userprofile_alter_bookmark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this interaction was created')),
                ('selected_answer', models.CharField(help_text='The incorrect answer option the user selected', max_length=5)),
                ('last_tested', models.DateTimeField(blank=True, help_text='When this weakness was last tested', null=True)),
                ('resolved', models.BooleanField(default=False, help_text='Whether this weakness has been resolved (user got it right later)')),
                ('mcq', models.ForeignKey(help_text='The associated MCQ', on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
                ('user', models.ForeignKey(help_text='User who interacted with this MCQ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incorrect Answer',
                'verbose_name_plural': 'Incorrect Answers',
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'resolved'], name='mcq_incorre_user_id_19c3ba_idx'), models.Index(fields=['user', 'last_tested'], name='mcq_incorre_user_id_a032a1_idx')],
            },
        ),
    ]
