# Generated by Django 5.2 on 2025-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0007_incorrectanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image for this question (if applicable)', null=True),
        ),
    ]
