# Generated by Django 5.2 on 2025-05-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0007_add_explanation_sections'),
        ('mcq', '0008_mcq_image_url'),
    ]

    operations = [
    ]
