# Generated by Django 5.2 on 2025-05-17 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0009_merge_20250515_1541'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='What the user thinks is the correct answer', max_length=1)),
                ('reason', models.TextField(help_text="User's explanation of why they think the current answer is wrong")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of this report', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this report')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this report was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this report was last updated')),
                ('question', models.ForeignKey(help_text='The MCQ being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mcq.mcq')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Report',
                'verbose_name_plural': 'Question Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mcq_questio_status_007c81_idx'), models.Index(fields=['question', 'user'], name='mcq_questio_questio_71390c_idx')],
            },
        ),
    ]
