# Generated by Django 5.2 on 2025-05-18 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0010_questionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighYieldSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('introduction', models.TextField(help_text='General overview of this specialty and its disorders')),
                ('historical_overview', models.TextField(help_text='Brief historical overview and current nosology')),
                ('important_concepts', models.TextField(help_text='Most important concepts')),
                ('related_anatomy', models.TextField(help_text='Related anatomy')),
                ('introduction_image', models.URLField(blank=True, help_text='Google Drive URL for introduction image')),
                ('anatomy_image', models.URLField(blank=True, help_text='Google Drive URL for anatomy image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specialties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'High-Yield Specialty',
                'verbose_name_plural': 'High-Yield Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HighYieldTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Order in which topic appears')),
                ('introduction_classification', models.TextField(blank=True, help_text='Introduction and classification')),
                ('pathology_pathophysiology', models.TextField(blank=True, help_text='Pathology and pathophysiology')),
                ('epidemiology', models.TextField(blank=True, help_text='Epidemiology')),
                ('clinical_presentation', models.TextField(blank=True, help_text='Clinical presentation and physical exam')),
                ('paraclinical_testing', models.TextField(blank=True, help_text='Para clinical testing')),
                ('diagnostic_criteria', models.TextField(blank=True, help_text='Diagnostic criteria')),
                ('differential_diagnosis', models.TextField(blank=True, help_text='Differential diagnosis')),
                ('management_guidelines', models.TextField(blank=True, help_text='Management guidelines')),
                ('prognosis', models.TextField(blank=True, help_text='Prognosis')),
                ('common_pitfalls', models.TextField(blank=True, help_text='Common pitfalls')),
                ('latest_guidelines', models.TextField(blank=True, help_text='Latest guidelines and evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mcq.highyieldspecialty')),
            ],
            options={
                'verbose_name': 'High-Yield Topic',
                'verbose_name_plural': 'High-Yield Topics',
                'ordering': ['specialty', 'order', 'title'],
                'unique_together': {('specialty', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TopicSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('introduction_classification', 'Introduction and Classification'), ('pathology_pathophysiology', 'Pathology and Pathophysiology'), ('epidemiology', 'Epidemiology'), ('clinical_presentation', 'Clinical Presentation'), ('paraclinical_testing', 'Para Clinical Testing'), ('diagnostic_criteria', 'Diagnostic Criteria'), ('differential_diagnosis', 'Differential Diagnosis'), ('management_guidelines', 'Management Guidelines'), ('prognosis', 'Prognosis'), ('common_pitfalls', 'Common Pitfalls'), ('latest_guidelines', 'Latest Guidelines')], help_text='Which section this image belongs to', max_length=50)),
                ('image_url', models.URLField(help_text='Google Drive URL for the image')),
                ('caption', models.CharField(blank=True, help_text='Caption for the image', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Order within the section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_images', to='mcq.highyieldtopic')),
            ],
            options={
                'verbose_name': 'Topic Section Image',
                'verbose_name_plural': 'Topic Section Images',
                'ordering': ['topic', 'section', 'order'],
            },
        ),
    ]
