# Generated by Django 5.2 on 2025-05-18 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0011_highyieldspecialty_highyieldtopic_topicsectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highyieldspecialty',
            name='historical_overview',
            field=ckeditor.fields.RichTextField(help_text='Brief historical overview and current nosology'),
        ),
        migrations.AlterField(
            model_name='highyieldspecialty',
            name='important_concepts',
            field=ckeditor.fields.RichTextField(help_text='Most important concepts'),
        ),
        migrations.AlterField(
            model_name='highyieldspecialty',
            name='introduction',
            field=ckeditor.fields.RichTextField(help_text='General overview of this specialty and its disorders'),
        ),
        migrations.AlterField(
            model_name='highyieldspecialty',
            name='related_anatomy',
            field=ckeditor.fields.RichTextField(help_text='Related anatomy'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='clinical_presentation',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Clinical presentation and physical exam'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='common_pitfalls',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Common pitfalls'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='diagnostic_criteria',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Diagnostic criteria'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='differential_diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Differential diagnosis'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='epidemiology',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Epidemiology'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='introduction_classification',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Introduction and classification'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='latest_guidelines',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Latest guidelines and evidence'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='management_guidelines',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Management guidelines'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='paraclinical_testing',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Para clinical testing'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='pathology_pathophysiology',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Pathology and pathophysiology'),
        ),
        migrations.AlterField(
            model_name='highyieldtopic',
            name='prognosis',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Prognosis'),
        ),
    ]
