# Generated by Django 5.2 on 2025-05-25 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0012_alter_highyieldspecialty_historical_overview_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mcq",
            name="ai_generated",
            field=models.BooleanField(
                default=False, help_text="Whether this question was AI-generated"
            ),
        ),
        migrations.AddField(
            model_name="mcq",
            name="correct_answer_text",
            field=models.TextField(
                blank=True, help_text="Text of the correct answer option", null=True
            ),
        ),
        migrations.AddField(
            model_name="mcq",
            name="fixed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the question was last fixed or updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcq",
            name="unified_explanation",
            field=models.TextField(
                blank=True,
                help_text="Unified explanation text for questions with single explanations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcq",
            name="word_count",
            field=models.IntegerField(
                blank=True, help_text="Word count of the explanation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mcq",
            name="exam_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of exam this question appeared in",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcq",
            name="exam_year",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Year the question appeared in an exam",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcq",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Answer options stored as JSON array, e.g., ['Option A', 'Option B', 'Option C', 'Option D']",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CaseLearningHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=100)),
                ("case_hash", models.CharField(max_length=20)),
                ("condition", models.CharField(max_length=200)),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "specialty", "-seen_at"],
                        name="mcq_caselea_user_id_152c96_idx",
                    )
                ],
                "unique_together": {("user", "case_hash")},
            },
        ),
        migrations.CreateModel(
            name="CaseLearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=50, unique=True)),
                ("specialty", models.CharField(max_length=100)),
                ("case_hash", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_state", models.CharField(default="INITIAL", max_length=50)),
                (
                    "patient_outcome",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("improving", "Improving"),
                            ("deteriorating", "Deteriorating"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "specialty"],
                        name="mcq_caselea_user_id_634101_idx",
                    ),
                    models.Index(
                        fields=["case_hash"], name="mcq_caselea_case_ha_fd89f8_idx"
                    ),
                ],
            },
        ),
    ]
