# Generated by Django 4.2.7 on 2025-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0013_mcq_ai_generated_mcq_correct_answer_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcq",
            name="correct_answer",
            field=models.CharField(
                help_text="Letter(s) of the correct answer option (A, B, C, D, etc. or comma-separated for multiple answers)",
                max_length=15,
            ),
        ),
    ]
