# Generated by Django 4.2.7 on 2025-05-28 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mcq", "0014_increase_correct_answer_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentCaseLearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("state", models.IntegerField(default=0)),
                ("specialty", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=20)),
                ("case_data", models.JSONField(default=dict)),
                ("chief_complaint", models.TextField(blank=True)),
                ("history_gathered", models.JSONField(default=list)),
                ("examination_findings", models.JSONField(default=list)),
                ("localization", models.JSONField(default=list)),
                ("investigations", models.JSONField(default=list)),
                ("differentials", models.JSONField(default=list)),
                ("management", models.JSONField(default=list)),
                ("critical_history_missed", models.JSONField(default=list)),
                ("critical_exam_missed", models.JSONField(default=list)),
                ("missed_critical_steps", models.JSONField(default=list)),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("auto_delete_after", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("screening_exam_done", models.BooleanField(default=False)),
                ("detailed_exam_areas", models.JSONField(default=list)),
                (
                    "patient_condition",
                    models.CharField(default="stable", max_length=50),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persistent_case_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Persistent Case Session",
                "verbose_name_plural": "Persistent Case Sessions",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="mcq_persist_user_id_b8a86b_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="mcq_persist_session_e1242f_idx"
                    ),
                    models.Index(
                        fields=["completed", "auto_delete_after"],
                        name="mcq_persist_complet_d05259_idx",
                    ),
                ],
            },
        ),
    ]
