# Generated by Django 4.2.7 on 2025-05-28 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mcq", "0015_persistentcaselearningsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitiveReasoningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answer",
                    models.CharField(
                        help_text="The answer option the user selected", max_length=5
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the selected answer was correct",
                    ),
                ),
                (
                    "user_reasoning",
                    models.TextField(
                        help_text="User's explanation of their reasoning process"
                    ),
                ),
                (
                    "primary_error",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anchoring_bias", "Anchoring Bias"),
                            ("confirmation_bias", "Confirmation Bias"),
                            ("availability_heuristic", "Availability Heuristic"),
                            ("premature_closure", "Premature Closure"),
                            ("overconfidence", "Overconfidence Bias"),
                            ("knowledge_gap", "Knowledge Gap"),
                            ("misconception", "Misconception"),
                        ],
                        help_text="Primary cognitive error identified",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "secondary_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional cognitive errors identified",
                    ),
                ),
                (
                    "knowledge_gaps",
                    models.JSONField(
                        blank=True, default=list, help_text="Identified knowledge gaps"
                    ),
                ),
                (
                    "misconceptions",
                    models.JSONField(
                        blank=True, default=list, help_text="Identified misconceptions"
                    ),
                ),
                (
                    "reasoning_quality",
                    models.CharField(
                        choices=[
                            ("poor", "Poor"),
                            ("fair", "Fair"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="fair",
                        help_text="Overall quality of reasoning",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence in the analysis (0.0-1.0)"
                    ),
                ),
                (
                    "guidance_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Step-by-step guidance content",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=0, help_text="Current step in the guidance process"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analyzing", "Analyzing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="analyzing",
                        help_text="Current status of the session",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if analysis failed",
                        null=True,
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helpful", "Helpful"),
                            ("somewhat_helpful", "Somewhat Helpful"),
                            ("not_helpful", "Not Helpful"),
                        ],
                        help_text="User's feedback on the guidance",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "feedback_comments",
                    models.TextField(
                        blank=True,
                        help_text="Additional user feedback comments",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this reasoning session was created",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the guidance was completed",
                        null=True,
                    ),
                ),
                (
                    "mcq",
                    models.ForeignKey(
                        help_text="The MCQ being analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mcq.mcq",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who participated in this reasoning session",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cognitive Reasoning Session",
                "verbose_name_plural": "Cognitive Reasoning Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="mcq_cogniti_user_id_3d7ca7_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="mcq_cogniti_status_83d9a6_idx",
                    ),
                    models.Index(
                        fields=["mcq", "user"], name="mcq_cogniti_mcq_id_13ba05_idx"
                    ),
                ],
            },
        ),
    ]
