# Generated by Django 4.2.7 on 2025-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0016_cognitivereasoningsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitivereasoningsession",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for background processing",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cognitivereasoningsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("analyzing", "Analyzing"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                    ("failed", "Failed"),
                ],
                default="analyzing",
                help_text="Current status of the session",
                max_length=20,
            ),
        ),
    ]
