# Generated by Django 4.2.7 on 2025-06-05 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mcq", "0017_add_task_id_to_cognitive_reasoning"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCQCaseConversionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Generated case data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the conversion",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for background processing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if conversion failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the conversion was requested"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the conversion was completed",
                        null=True,
                    ),
                ),
                (
                    "mcq",
                    models.ForeignKey(
                        help_text="The MCQ being converted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_conversions",
                        to="mcq.mcq",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who requested the conversion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_case_conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ Case Conversion Session",
                "verbose_name_plural": "MCQ Case Conversion Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "mcq"], name="mcq_mcqcase_user_id_756639_idx"
                    ),
                    models.Index(
                        fields=["status"], name="mcq_mcqcase_status_de6244_idx"
                    ),
                ],
            },
        ),
    ]
